### ISSUE TITLE
[conan center] check there is no imports in test_package/conanfile.py

### ISSUE THREAD

**Issue by SSE4** [conan-io/hooks#101]
seems like `imports` method is not needed in **test_package/conanfile.py**, if we use `run_environment`?

**Comment by danimtb** [comment]
I shouldn't be necessary. We can prepare the hook to do the check in both the library recipe and the test package

**Comment by SSE4** [comment]
yeah, in my practice, I never needed `imports` in recipes and tests, maybe @uilianries and @Croydon have something on mind

**Comment by uilianries** [comment]
Maybe for res/ folder, but I can't remember some case. It should be okay preventing it from test_package
