### ISSUE TITLE
[conan center] fail on linter warnings

### ISSUE THREAD

**Issue by SSE4** [conan-io/hooks#107]
disclaimer: not sure if it belongs here at all
currently, some cci recipes have linter warnings, e.g. `libpng`:
```
Linter warnings
    WARN: Linter. Line 6: Unused ConanException imported from conans.errors
```
it would be nice if hook rejects such recipes

**Comment by uilianries** [comment]
The only that I remember which could cause false-positive is when we have split recipes, e.g. protobuf, flatbuffers, where we need to load a base recipe as an external module and the linter can't detect that situation. Of course, for CCI it's not a problem, so I think this hook sounds good.
