### ISSUE TITLE
[conan center] check there are no scm and revision mode attributes

### ISSUE THREAD

**Issue by SSE4** [conan-io/hooks#135]

**Comment by danimtb** [comment]
Did it happen already? I mean, is there a PR that triggered this issue?

**Comment by SSE4** [comment]
yes, there was on with SCM, but I forget which one, will try to find it

**Comment by SSE4** [comment]
it was [picojson](https://github.com/conan-io/conan-center-index/pull/373#event-2832419463)

**Comment by uilianries** [comment]
Good catch!
