### ISSUE TITLE
[CI] Fix test running with python 2

### ISSUE THREAD

**Issue by danimtb** [conan-io/hooks#146]
In the development version of conan (1.22), python 2 is deprecated on purpose.

We should set `USE_UNSUPPORTED_CONAN_WITH_PYTHON_2` variable in the CI for Conan dev > 1.21.X

Related to #145

**Comment by jgsogo** [comment]
Add it to the `.travis.yml` and `appveyor.yml` files in the entries for current `conandev` (we will need to move it when rolling releases, but eventually it will disappear), IMO it is better than adding it to the actual testing sources
