### ISSUE TITLE
Python 2.7 tests are broken

### ISSUE THREAD

**Issue by uilianries** [conan-io/hooks#162]
When checking the PR https://github.com/conan-io/hooks/pull/161, some tests failed, but all them are old tests. It's only failing with python 2.7

**Comment by danimtb** [comment]
Master branch is green https://travis-ci.org/conan-io/hooks/builds/654455620 I don't know what is the issue 😕

**Comment by uilianries** [comment]
I'll check this one later, I want to put some effort on hooks during this week.

**Comment by uilianries** [comment]
Closing this one, since the possible problem is caused by #161 tests (EOL).
