### ISSUE TITLE
[conan-center-index] enable CONAN_V2_MODE?

### ISSUE THREAD

**Issue by SSE4** [conan-io/hooks#170]
maybe it makes sense to enable **CONAN_V2_MODE** to earlier detect compatibility problems?
WDYT @uilianries @danimtb ?

**Comment by uilianries** [comment]
We can add a extra build with it, but not for all builds. It's not a enabled by default.

**Comment by memsharded** [comment]
Nop. CONAN_V2_MODE might eventually break things badly. We certainly don't want to affect users PRs with potential false positives or affect the build (maybe can generate a different packageID!!).

It might be ok to run an informative build for us, raising potential issues, like nightly or weekly.

**Comment by uilianries** [comment]
> nightly or weekly.

Yes, it's possible creating a nightly/weekly build in Travis.

**Comment by danimtb** [comment]
I think this is outdated and can be closed now
