### ISSUE TITLE
[conan center] check CMAKE_VERBOSE_MAKEFILE 

### ISSUE THREAD

**Issue by SSE4** [conan-io/hooks#188]
from https://github.com/conan-io/conan-center-index/pull/1485/files#r416636412
some recipes are using `CMAKE_VERBOSE_MAKEFILE` in their **CMakeLists.txt** or **test_package/CMakeLists.txt**.
/cc @uilianries

**Comment by Croydon** [comment]
I don't recall this discussion about using it or not. Could you provide a short summary?

**Comment by SSE4** [comment]
I think we have decided not to use it within recipe. we're removing it if it was already there.

**Comment by Croydon** [comment]
Understood, but why?

**Comment by uilianries** [comment]
Log size, IMO

But, when I build at home, I enable all verbose stuff to check the compiler flags.

**Comment by madebr** [comment]
If verbose logging is really required and you are using the cmake build helpers,
you can always use its `verbose` attribute. That might work on more generator backends.
