### ISSUE TITLE
[bug] members_typo_checker reporting python_requires_extend as typo

### ISSUE THREAD

**Issue by cguldner** [conan-io/hooks#189]
```
[HOOK - members_typo_checker.py] pre_export(): WARN: The 'python_requires_extend' member looks like a typo. Similar to:
[HOOK - members_typo_checker.py] pre_export(): WARN:     python_requires
```

**Comment by cguldner** [comment]
@uilianries I could put out a PR for this fairly quickly if you give me contributor privileges

**Comment by uilianries** [comment]
@cguldner You don't need extra privileges, anyone is able to open a PR to conan-io/hooks, you only need a Github account. Regards.

**Comment by cguldner** [comment]
@uilianries I wasn't able to create a branch

**Comment by uilianries** [comment]
@cguldner Please, create a fork: https://github.com/conan-io/hooks/fork

After that, you will be able to upload anything to your copy and open a PR from there. Regards.
