### ISSUE TITLE
[conan-center] Do not allow range version for requirements

### ISSUE THREAD

**Issue by uilianries** [conan-io/hooks#203]
It's rare, but I saw some newbies adding recipes using version for requirements `[>1.70]/boost`

It would be nice a hook which allows only specific versions.

**Comment by Croydon** [comment]
Don't we already have this?

**Comment by Croydon** [comment]
Yes: https://github.com/conan-io/hooks/blob/a83ed36c9cc5d122072b56f2ae972975c072084f/hooks/conan-center.py#L178

**Comment by uilianries** [comment]
hmm, probably false alarm, because the user was not EAP, which is the first step before running the CI bot for hooks/build.
