### ISSUE TITLE
[conan-center] Make topics attribute mandatory in recipes

### ISSUE THREAD

**Issue by danimtb** [conan-io/hooks#210]
One of the new upcoming features of the ConanCenter UI will be the search by topic. However, I have realized that this attribute is not enforced by the hook right now, so we may consider adding it.

One example of this is https://github.com/conan-io/conan-center-index/blob/master/recipes/glog/all/conanfile.py

**Comment by uilianries** [comment]
Maybe we should consider some mandatory topics, like `header-only`, `installer` ...

**Comment by danimtb** [comment]
hard to tell if we can be so smart, but at least we need the topics' attribute with something there so the search can be done

**Comment by uilianries** [comment]
we already have hooks which is able to detect both, so I don't think it's a problem.
