### ISSUE TITLE
[conan-center] Create check that static libraries are the default

### ISSUE THREAD

**Issue by Croydon** [conan-io/hooks#217]
Why we need this hook, e.g.: https://github.com/conan-io/conan-center-index/issues/2566

We already de-facto enforce through reviews that static libraries should be the default option

I propose that we are adding a check to the hook enforcing this automatically with an allowlist for special cases where this might be unwanted

Recipes who don't support shared building won't have the `shared` option and the hook would not complain

**Comment by Croydon** [comment]
Recipes who currently set 

> default_options = {"shared": True}

backward-cpp
botan
glib
libb2
libepoxy
libsigcpp
paho-mqtt-c
tbb
xkbcommon

**Comment by Croydon** [comment]
@ericLemanissier We need to add glib to an allowlist too because it does not support static on Windows, right?

**Comment by ericLemanissier** [comment]
Yes https://gitlab.gnome.org/GNOME/glib/-/issues/692

**Comment by uilianries** [comment]
Backward-cpp does not require shared by default: https://github.com/conan-io/conan-center-index/pull/2598

**Comment by Croydon** [comment]
@uilianries Thanks for helping!

**Comment by jgsogo** [comment]
Thank you two for taking care of this. I also think this is a good default 🙌

**Comment by uilianries** [comment]
Backward-cpp: conan-io/conan-center-index#2598
Blake2 (libb2): https://github.com/conan-io/conan-center-index/pull/2601
libsigcpp: https://github.com/conan-io/conan-center-index/pull/2603
libepoxy: https://github.com/conan-io/conan-center-index/pull/2602
Botan: https://github.com/conan-io/conan-center-index/pull/2614
xkbcommon: https://github.com/conan-io/conan-center-index/pull/2613


TBB: does not officially support static lib: https://github.com/oneapi-src/oneTBB/issues/221#issuecomment-633561961

**Comment by Croydon** [comment]
All done

Thanks everyone 👏
