### ISSUE TITLE
[conan-center] H016 does not display any files

### ISSUE THREAD

**Issue by Croydon** [conan-io/hooks#230]
See e.g. https://github.com/conan-io/conan-center-index/pull/2720#issuecomment-686629446

> [HOOK - conan-center.py] post_package(): ERROR: [CMAKE-MODULES-CONFIG-FILES (KB-H016)] Found files:

**Comment by ericLemanissier** [comment]
this bug is probably on the bot, more than on the hooks,because if you look at create_stderr.txt, you get the file list

**Comment by mathbunnyru** [comment]
I think it's probably because the error is several lines or something like that.

```
[HOOK - conan-center.py] post_package(): ERROR: [CMAKE-MODULES-CONFIG-FILES (KB-H016)] Found files:
./lib/cmake/mFAST/mFASTConfig.cmake (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H016) 
```

**Comment by uilianries** [comment]
The hook works correctly, however, Github doesn't show new lines. If you read the log error, all files are listed there.

**Comment by Croydon** [comment]
You are right. Not a hook error, but rather a CCI bot error.

I'm opening an issue on CCI.
