### ISSUE TITLE
Check that requires and requirements() do not exist simultaneously

### ISSUE THREAD

**Issue by mathbunnyru** [conan-io/hooks#254]
As @SpaceIm suggested in the PR review:
https://github.com/conan-io/conan-center-index/pull/3681#pullrequestreview-537524674

> requires() should be called in requirements() + it's better to put requirements close to each others (harder to understand dependencies in the recipe if they are split in requires attribute and requirements())

**Comment by SpaceIm** [comment]
Maybe a suggestion for https://github.com/conan-io/conan-center-index/pull/3614?

**Comment by mathbunnyru** [comment]
@SpaceIm I added a suggestion.

**Comment by uilianries** [comment]
It sounds good!
