### ISSUE TITLE
Disallow illegal characters in filenames

### ISSUE THREAD

**Issue by madebr** [conan-io/hooks#298]
Windows puts more limitations on what characters a valid filename can contain.
Using an invalid character, e.g. a `:`, causes weird problems in c3i.
See https://github.com/conan-io/conan-center-index/pull/5583

Maybe it would be interesting to create a hook (or amend a hook) to check whether all filenames are valid?

Windows naming conventions:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

**Comment by uilianries** [comment]
Move to Linux, problem solved 😈 🐧 

Besides the joke, it's a valid case indeed, thanks for suggesting.
