### ISSUE TITLE
How to test plugins?

### ISSUE THREAD

**Issue by uilianries** [conan-io/hooks#3]
Hi!

It would be nice add some tests for new plugins but using `conan config` to install, all tests will be copied also.

Is there some way to ignore those files using `conan config install` ?

**Comment by danimtb** [comment]
Yes, this is something that has to be discussed too. The plugins feature is still on its early stages 😄

**Comment by jgsogo** [comment]
Already implemented, I think that the current approach is flexible and powerful enough 💪

**Comment by uilianries** [comment]
Thanks guys!
