### ISSUE TITLE
Broken OSX Travis CI jobs

### ISSUE THREAD

**Issue by uilianries** [conan-io/hooks#301]
The PR #300 failed due a suspicious error involving Travis and its OSX jobs.

https://travis-ci.org/github/conan-io/hooks/builds/773294565

I deserves a further investigation.

/cc @jgsogo

**Comment by Croydon** [comment]
Unless the Conan team is willing to regularly request new credits from Travis, it will stop running eventually anyway. 

See https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

Maybe migrate to GitHub Actions?

**Comment by uilianries** [comment]
That's a possibility which I would vote, but probably team will vote for Jenkins, because is under their control.

**Comment by jgsogo** [comment]
Yes, we need to migrate from Travis/Appveyor. Github-Actions is ok, our Jenkins is another alternative. This is a very small project, so I think we shouldn't consider any other factors.

**Comment by Croydon** [comment]
This can be closed
