### ISSUE TITLE
Use cases for `tools.os_info` inside recipes: only during _build_ step? 

### ISSUE THREAD

**Issue by jgsogo** [conan-io/hooks#303]
Can be added to `conan-center` hookL https://github.com/conan-io/conan-center-index/pull/5746#issuecomment-854495070

Does anyone see a valid scenario?

**Comment by ericLemanissier** [comment]
It is used at least in all system packages, in order to identify the distribution

**Comment by jgsogo** [comment]
That's a good point. All of them inside `system_requirements()` method (same context as `build()` method).

These are packages installed in the running machine and [always] match the running architecture, so they are suitable only for _native_ builds. These recipes should raise in cross-building scenarios. Then, information about os and arch must be retrieved from the profile and `tools.os_info` used only to get the underlying package manager (`with_yum`, `with_apt`,...). IMHO, it should be better to get this information somehow through the `SystemPackageTool` class (possible feature, not available in Conan right now).

**Comment by ericLemanissier** [comment]
Really ? I thought `SystemPackageTool` added a suffix to package names, according to the arch ? in https://docs.conan.io/en/1.36/reference/conanfile/methods.html#method-system-requirements: `The SystemPackageTool is adapted to support possible prefixes and suffixes, according to the instance of the package manager. It validates whether your current settings are configured for cross-building, and if so, it will update the package name to be installed according to self.settings.arch.`

**Comment by jgsogo** [comment]
Depending on the system package manager, the recipes are selecting different packages. It is not enough with the logic inside that class. For example, `gtk` recipe:

```python

    def system_requirements(self):
        packages = []
        if tools.os_info.is_linux and self.settings.os == "Linux":
            if tools.os_info.with_apt:
                packages = ["libgtk2.0-dev"] if self.options.version == 2 else ["libgtk-3-dev"]
            elif tools.os_info.with_yum or tools.os_info.with_dnf:
                packages = ["gtk{}-devel".format(self.options.version)]
            elif tools.os_info.with_pacman:
                packages = ["gtk{}".format(self.options.version)]
            elif tools.os_info.with_zypper:
                packages = ["gtk{}-devel".format(self.options.version)]
            else:
                self.output.warn("Do not know how to install 'GTK-{}' for {}."
                                 .format(self.options.version,
                                         tools.os_info.linux_distro))
```

**Comment by ericLemanissier** [comment]
AFAIU, this work is not done by the recipe, but by conan itself: https://github.com/conan-io/conan/blob/c2ad7201f0c67c403e9d9257b6b95a0a30744106/conans/client/tools/system_pm.py#L295

**Comment by jgsogo** [comment]
Probably that logic is not enough sometimes. Anyway, I feel like those `tools.os_info.with_apt`, `tools.os_info.with_yum`,... could be replaced by some function call to `SystemPackageTool` instead of using `os_info`. And even more, if there is already some logic inside that class that is using that information.

**Comment by SSE4** [comment]
right now, we allow `tools.os_info` in the `build` step only (it is validated by KB-H061. for `build`, there are valid usages (e.g. many recipes need `win_bash = tools.os_info.is_windows`).
in other methods, it usually only causes errors hard to catch (e.g. package ID is computed differently on Linux vs macOS nodes).
