### ISSUE TITLE
[feature] Recipe with configuration to skip hook parts

### ISSUE THREAD

**Issue by uilianries** [conan-io/hooks#310]
When a new CCI recipe comes and for some reason, there is an exception which should be considered by Conan Center hook, we have to update the Conan Center hook manually and people need to update their local copies. This monkey job could be improved if we use the `config.yml` instead, to list any incompatible hook, for instance:

```yml
# config.yml
versions:
  "5.4.1":
    folder: all
    
skipped-hooks:
  - 014
```

Where `skipped-hooks` are KB number from Conan Center which will be ignored.

On the other side, Conan Center hook will read the config.yml, parse that keys and skip what is listed.

Pros:
- Quick update on PRs, no longer need to wait for Hooks second PR
- Users won't be so frustrated when waiting for hook PR
- Don't need to update hook locally after a single update

Cons:
- Users can configure what should be skipped
- Reviewers will need to confirm if any skip is legit

**Comment by Croydon** [comment]
I'm against that. This will decrease the barrier to make exceptions, so more hook exceptions will be made for sure. Probably also in more cases than they should be made.

**Comment by danimtb** [comment]
I think this has come up earlier in some conversations and agreed that we don't want right now an easy way to bypass the checks. I know the current approach might be uncomfortable in some cases but I think it is better to keep it this way.

Also, this would couple the config file to the behavior of the hooks and local testing will not achieve the same behavior as the C3I one

**Comment by uilianries** [comment]
Thank you for your points of view. Indeed the Cons are worst than I could imagined.
