### ISSUE TITLE
[conan-center] Do not allow CR LF as endline

### ISSUE THREAD

**Issue by uilianries** [conan-io/hooks#313]
Related to https://github.com/conan-io/conan-center-index/pull/6055

So far, only ./folly/all/test_package/test_package.cpp uses CRLF and Platform.Interfaces

How to find it?

    cd conan-center-index/recipes && find . -not -type d -exec file "{}" ";" | grep CRLF

**Comment by SSE4** [comment]
why hook? couldn't it be detected/enforced by .gitattributes, for instance?

**Comment by uilianries** [comment]
Yes, but should be done on CI side. This [comment](https://github.com/conan-io/conan-center-index/pull/6055#issuecomment-868011128) resumes my surprise. This hook helps users to see any error locally.
