### ISSUE TITLE
Visual Studio 2019 (version 16) is not supported by binary_linter

### ISSUE THREAD

**Issue by fdgStilla** [conan-io/hooks#323]
https://github.com/conan-io/hooks/blob/ee4dd5f49f56d9d970d2fb25421776b974f5103b/hooks/binary_linter.py#L153 => range should be 17, otherwise the hook exit with error ERROR: [HOOK - binary_linter.py] post_package(): '16' because version 16 is not inserted in list of known versions.

**Comment by SSE4** [comment]
related: https://github.com/conan-io/conan/issues/9362
