### ISSUE TITLE
Link to "inclusion guidelines of third-party libraries"

### ISSUE THREAD

**Issue by garethsb** [conan-io/hooks#339]
https://github.com/conan-io/hooks#conan-center contains the following lin, [inclusion guidelines of third-party libraries](https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries), which is broken.

Where should it now point? Maybe https://docs.conan.io/en/latest/uploading_packages/artifactory/conan_center_guide.html? Or https://github.com/conan-io/conan-center-index/blob/master/docs/contributing.md?

**Comment by uilianries** [comment]
@garethsb Thanks for your report! Indeed that link is broken and now Conan Center is the new one.

The first link (https://docs.conan.io/en/latest/uploading_packages/artifactory/conan_center_guide.html) is the correct one, as it points to docs.conan.
