### ISSUE TITLE
[conan-center] Check that os/arch/compiler/build_type settings are defined

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/hooks#371]
conan v2 requires to always define these settings, regardess of their usage in the recipe (they can be deleted in package_id() if they don't contribute to packaged files).
A conan-center hook should be added to support transition to conan v2. Moreover it's harmless for conan v1.

https://github.com/conan-io/conan-center-index/issues/8237
https://github.com/conan-io/conan-center-index/issues/8238

Probably one of the hooks required for https://github.com/conan-io/hooks/issues/370

**Comment by jgsogo** [comment]
I really like to have always all the settings... in fact, I suggested that the `Conanfile` class should **by default** declare all (first level) settings.
