### ISSUE TITLE
[conan-center] Add a hook to check whether installed shared libs are relocatable on Linux & macOS

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/hooks#376]
Currently, many recipes don't produce state of the art relocatable shared libs on macOS.

It would be nice to check whether shared libs on macOS properly have `@rpath/<shared>` in install tree (`@rpath` token is supported since macOS 10.5 Leopard, so since 2007...).
It must not be `<shared>` or `<absolute/path/to/shared>` (many binaries produced by conan-center recipes on macOS have the former actually, it's bad).
see https://cmake.org/cmake/help/latest/prop_tgt/MACOSX_RPATH.html#prop_tgt:MACOSX_RPATH

Moreover, rpath should be empty in installed shared libs.
Usually, in a default CMake configuration, binaries produced in build tree have absolute paths of dependencies (direct & transitive) libs folder in their rpath, so that you can run your executable for free (on macOS, it only works if external shared libs also have `@rpath` token, so proper relocatable binaries), then it is cleared by CMake during installation.

It also means that all CMake based recipe must:
- use `conan_basic_setup(KEEP_RPATHS)`
- recipe should ensure that https://cmake.org/cmake/help/latest/policy/CMP0042.html#policy:CMP0042 is enabled (either by injection `CMAKE_POLICY_DEFAULT_CMP0042 NEW`, or ensuring `cmake_minimum_required(VERSION 3.0)` or higher in upstream CMakeLists).
- recipe should call install target, not manually copying files (it can be allowed if target os is Windows), so that CMake can:
   - eventually replace absolute path set in shared libs of the build tree with `@rpath` for shared libs in install tree (usually it's already `@rpath` in the build tree, but not always).
   - clear rpath (and it's also important on Linux). To do so, `CMAKE_INSTALL_RPATH` & `CMAKE_INSTALL_RPATH_USE_LINK_PATH` should not be manipulated.
  
   If manual copy can't be avoided, something like this at the end of `package()` may allow to add `@rpath` token into dylib files :
   ```python
    if tools.is_apple_os(self.settings.os):
        with tools.chdir(os.path.join(self.package_folder, "lib")):
            for dylib in glob.glob("*.dylib"):
                command = "install_name_tool -id {0} @rpath/{1}".format(os.path.basename(dylib), dylib)
                self.run(command)
    ```

I suspect that many issues consumers have with "all shared" builds (`-o *:shared=True`) on macOS would be solved. Default behavior of `conan_basic_setup` on macOS is really harmful.

see https://github.com/conan-io/conan-center-index/issues/9052
also https://github.com/conan-io/conan/issues/1238 or https://github.com/conan-io/conan/issues/10253
https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/RunpathDependentLibraries.html
https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling#mac-os-x-and-the-rpath
https://www.mikeash.com/pyblog/friday-qa-2009-11-06-linking-and-install-names.html

**Comment by uilianries** [comment]
It sounds interesting

**Comment by SpaceIm** [comment]
Regarding autotools builds, it's worse, path of build machine is hardcoded in installed shared libs on macOS. Maybe this thread in spark package manager would help to fix these recipes: https://github.com/spack/spack/pull/26608#

**Comment by SpaceIm** [comment]
Proposal:

Linux:

- for each shared lib (not the symlinks) in the install tree of the recipe, check that `objdump -x <libname> | grep RUNPATH` doesn't return anything (no more hardcoded runpath to dependencies).

macOS:

- for each shared lib (not the symlinks) in the install tree of the recipe:
  -  run `otool -L <libname>`:
     - check that it can find `@rpath/<libname>` (don't be too strict about libname because it might be soversion, while the concrete file should have the lib version in its name).
     - check that for each shared dependency libN, if <libN> is found in above command, it is of the form `@rpath/<libN>` (again, don't be too strict) => It requires to visit all cpp_info.libs of the dependency tree.
  - check that `otool -l <libname> | grep LC_RPATH` doesn't return anything (no more hardcoded runpath to dependencies).

**Comment by gabyx** [comment]
@SpaceIm: This PR is really interesting and very very good I think. Your analysis covers exactly what we have problems with the recipes from Conan Center.

I have another technical question regarding `RPATH` (not regarding this PR):

- You said that putting all paths to libs (also transitive dependencies) (`A.so` loads `B.so`) into an *executable* `exe` which was linked with libs from conan package `A` (where `A` needs `B`) resolves all libs at startup??

Is that really the case: I experienced that even if `exe` contains RPATHs to `A.so` and `B.so` and a load instruction to `A.so` (because linked to it), causes the library find mechanism to fail, that is `B.so` is not found. It seems that the RPATH in the `exe` is not transitively used when loading transitive libraries (here `B.so`, as seen on ubuntu). Do you have generally the impression that it should be or what is the beahvior of the RPATH entry for transitive loads (loading `B.so` requested by `A.so`). Thanks a lot for your insights.

**Comment by SpaceIm** [comment]
> I have another technical question regarding `RPATH` (not regarding this PR):
> 
> * You said that putting all paths to libs (also transitive dependencies) (`A.so` loads `B.so`) into an _executable_ `exe` which was linked with libs from conan package `A` (where `A` needs `B`) resolves all libs at startup??
> 
> Is that really the case: I experienced that even if `exe` contains RPATHs to `A.so` and `B.so` and a load instruction to `A.so` (because linked to it), causes the library find mechanism to fail, that is `B.so` is not found. It seems that the RPATH in the `exe` is not transitively used when loading transitive libraries (here `B.so`, as seen on ubuntu). Do you have generally the impression that it should be or what is the beahvior of the RPATH entry for transitive loads (loading `B.so` requested by `A.so`). Thanks a lot for your insights.

On macOS, I'm pretty sure it works even for transitive dependencies. But here you are talking of .so, so Linux. I need to check.

**Comment by gabyx** [comment]
Thanks, a CMake MWE on Github would be nice so we can investigate also. I wanted to do it too but ive you habe time

**Comment by SSE4** [comment]
> Thanks, a CMake MWE on Github would be nice so we can investigate also. I wanted to do it too but ive you habe time

what is CMake MWE?

**Comment by gabyx** [comment]
Cmake minimal working example

Von meinem iPhone gesendet

**Comment by gabyx** [comment]
The following bug report is especially important as it give insight how DT_RPATH and DT_RUNPATH actually work:

https://bugs.launchpad.net/ubuntu/+source/eglibc/+bug/1253638

> It looks like it's the expected behaviour after all. From "Shared Object Dependencies" section in [1]:
  """
  The set of directories specified by a given DT_RUNPATH entry is used to find only the immediate   dependencies of the executable or shared object containing the DT_RUNPATH entry. That is, it is used   only for those dependencies contained in the DT_NEEDED entries of the dynamic structure containing   the DT_RUNPATH entry, itself. One object's DT_RUNPATH entry does not affect the search for any other   object's dependencies.
  """
  [1] https://refspecs.linuxfoundation.org/elf/gabi4+/ch5.dynamic.html#shobj_dependencies

**Comment by gabyx** [comment]
So what I get is the following:

Linux:
 - `RPATH`: .so files, transitive
 - `RUNPATH`: exes, and .so files, not transitive.
mostly `RUNPATH` is used (as it was made to replace `RPATH` which is still existing)


MacOS: 
 - The `@rpath` is (did not find the docs) transitive as you say.

**Comment by SpaceIm** [comment]
`conan-center` cannot set RPATH nor RUNPATH in installed shared libs, because paths of dependencies is not known (even relative paths).

**Comment by gabyx** [comment]
Ah ok. I had in mind that Conan could because it has the full knowledge of the dep. tree, modify shared libs RUNPATHs to make sure they work as intended. Such a mechanism would then also give the possibility to install a package an all its contents to an external folder which is itself selfcontaining (no external shared lib loads) etc. Whats the reason of immutability of package contents? I mean now the packages only work together by basically having this virtualrunenv wrapper which in turn does not modify the package and acts as the glue to make resolve loading dep chains.
