### ISSUE TITLE
- [conan-center] KB-H054 error message is too obscure

### ISSUE THREAD

**Issue by SSE4** [conan-io/hooks#379]
example https://github.com/conan-io/conan-center-index/pull/9223
```
ERROR: [LIBRARY DOES NOT EXIST (KB-H054)] Component libuv::libuv library "uv" not found in libdirs (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H054) 
```

I personally don't understand what should be done from the message
I think it requires a better wording

**Comment by uilianries** [comment]
It says the library `libuv` was declared in the recipe, but didn't find a file with this name in libdirs. Anyway, I see your point, and deserves an improvement.
