### ISSUE TITLE
[bintray-update] Wont work with conan_server

### ISSUE THREAD

**Issue by uilianries** [conan-io/hooks#41]
Hi!

When running conan_server, the hooks bintray-update shown:

```
[HOOK - bintray_update.py] post_upload_recipe(): ERROR: Could not extract subject and repo from http://0.0.0.0:9300: Invalid pattern
```

We need to check before to extract the information if the endpoint is Bintray.

**Comment by danimtb** [comment]
Makes sense. Maybe it is even better to add a check for "bintray" in the remote url.

I guess this will also happen with an artifactory repo, right?

**Comment by uilianries** [comment]
No idea, but I've tried to find some *ping* method over [Bintray API](https://bintray.com/docs/api/), unfortunately, no luck :disappointed:

**Comment by jgsogo** [comment]
The _Limits_ endpoint is usually used as a _ping_ one (usually it doesn't count for the rate limit)... and it will let us know if there are enough API calls left to run the plugin.

Nevertheless, I think it is too early to optimize it (we have to leave some minor issues for the less experienced people to contribute)

**Comment by uilianries** [comment]
The problem was not the ping, but the bad message. Actually this hook checks for the server address before to run, if the remote url does not contain a Bintray address, it will be aborted.

I though about the ping, because I understood the hook was trying to extract information from the remote, even for local server.
