### ISSUE TITLE
KB-H030 incompatible with projects hosted on googlesource.com

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/hooks#414]
projects hosted on googlesource.com provide archives with non-stable hash. The archive seem to be regenerated at least several times a day (maybe for each download request ?). 

- https://github.com/conan-io/conan-center-index/pull/10688
- https://github.com/conan-io/conan-center-index/pull/10689
- https://github.com/conan-io/conan-center-index/pull/10690
- https://github.com/conan-io/conan-center-index/pull/10691
- https://github.com/conan-io/conan-center-index/pull/10692

The best solution is to disable the check for sha256 attribute if the url starts with `https://*.googlesource.com`

**Comment by jcar87** [comment]
Indeed it looks like the archived tarballs from `googlesource.com` are generated upon request, and the metadata changes each time (the contents are the same):

https://github.com/google/gitiles/issues/84
