### ISSUE TITLE
Should we rename hooks?

### ISSUE THREAD

**Issue by danimtb** [conan-io/hooks#44]
When I started the conan-center hook I thought it would make sense to call it the same way as the remote ``conan-center``.

Having a look at the existing hooks I would like to have the naming "somehow" unified.

This is my proposal:

- *binary-linter.py* --> *binary_linter.py*
- *bintray_update.py* --> *bintray_updater.py*
- *github-updater.py* --> *github_updater.py*

Should we rename *conan-center.py* to something like *conan-center_reviewer.py* or *conan-center_checker.py* ?

cc/ @conan-io/community-leaders

**Comment by uilianries** [comment]
I approve your idea! :100: 

* `-` is not good for Python import, `_` is the best option IMO
* Since hooks execute some action, the new names fits better
* We could follow it to use the template name for the next hooks, and update the README with this information.

**Comment by SSE4** [comment]
yep, I also approve, let's use underscore instead. besides reasons mentioned above, minus/dash/hyphen is also very ambiguous character (there are around 10 of them of various appearance), so it's large source of errors.

**Comment by jgsogo** [comment]
It makes sense, rename them. But keep in mind that the _main file_ of each hook should never be imported using python machinery, it is a path, not a python module.

**Comment by uilianries** [comment]
Not, but maybe could be imported for unit tests only :wink:

**Comment by jgsogo** [comment]
> Not, but maybe could be imported for unit tests only 😉

Do not open a door that should be closed just because of the tests, someone will start to use it in production 🍭
