### ISSUE TITLE
Combinability with conan 2.0.

### ISSUE THREAD

**Issue by n-bes** [conan-io/hooks#465]
Hi.
I wanted to rebuild ```conan-center-index``` with ```conan```-v2 and enabled hooks.

I use these commands for ```conan```-v1:
```bash
pip3 install conan
conan config install https://github.com/conan-io/hooks.git
conan config set hooks.conan-center
```

Unfortunately, it's not working for conan-v2:
```
conan config set hooks.conan-center

conan config: error: argument subcommand: invalid choice: 'set' (choose from 'home', 'install', 'list')
ERROR: Exiting with code: 2
ERROR: executor failed running [/bin/sh -c conan config install https://github.com/conan-io/hooks.git &&     conan config set hooks.conan-center]: exit code: 2
```

So, i have two question:
1. Are the current hooks compatible with ```conan```-v2?
2. How to enable hooks for ```conan-```-v2? ```CONAN_V2_MODE```?

**Comment by RubenRBS** [comment]
Hi! The error you're experiencing is expected, as hooks have not yet been implemented in 2.0 due to api changes. (And so there's currently no way to enable them either)

The current plan is for them to be ready at the 2.0 launch, but we've been quite busy and we haven't yet managed to do the necessary changes :/

If they are available in a future beta release I'll make sure to let you know :)

**Comment by uilianries** [comment]
I started an effort on it and I have to say we will need to create a new hook.

Conan v2 uses a different method signature, which is incompatible with current hooks.

Also, many hooks could be managed by ConanCenterIndex linters, much better for code review and user feedback.

As result, the conan-center hook for Conan v2, will be much smaller and separated from the current one. The current conan-center hook should be deprecated in the future, as soon as Conan v2 become the main version in ConanCenterIndex.

**Comment by tim-goto** [comment]
Hey, is there already development effort for the hooks managed by ConanCenterIndex linters? Can I run them locally as well? How can I help?

**Comment by uilianries** [comment]
@tim-goto There is an initial effort, yes. You need to copy https://github.com/conan-io/hooks/blob/master/hooks/disabled-hook_conan-center-v2.py to your hook folder and rename according to the documentation: https://docs.conan.io/2/reference/extensions/hooks.html#storage-activation-and-sharing

Be aware, we will change that hook in the future, as many improvements in Conan 2.0 no longer reflect rules in that hook.

**Comment by n-bes** [comment]
> How to enable hooks for conan-v2? 

It is not supported. See #489
