### ISSUE TITLE
How to remove cppstd from pure C projects?

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/hooks#471]
Ran into this https://github.com/conan-io/conan-center-index/pull/15097#issuecomment-1370130669 and seeing  https://github.com/conan-io/hooks/blob/52ceef034f4ce1afa1e3db3196cc7e6a25b1e0bd/hooks/conan-center.py#L1024
it seems a touch restrictive, I would have expected 

```py
self.settings.compiler.rm_safe("cppstd")
self.settings.compiler.rm_safe("libcxx")
```

to work just as well as

```py

self.settings.rm_safe("compiler.cppstd")
self.settings.rm_safe("compiler.libcxx")
```

It seems are one point this was allowed 🤔 

https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index%20rm_safe(%22libcxx%22)&type=code

**Comment by uilianries** [comment]
@prince-chrismc The `self.settings.rm_safe("compiler.cppstd")` is safest approach in case the recipe does not have `compiler` listed in settings, the `self.settings.compiler.rm_safe("libcxx")` would fail with a Conan exception like this:

```
conans.errors.ConanException: 'settings.compiler' doesn't exist
'settings' possible configurations are ['arch', 'build_type', 'os']
```

It's true we have a hook to check settings, but it's a warning only.

Anyway, both `self.settings.compiler.rm_safe("cppstd")` are `self.settings.rm_safe("compiler.libcxx")` are valid IMHO.
