### ISSUE TITLE
conan-center hook KB-H075 has a false positive when giving example in comments about what consumer should do

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/hooks#473]
The hooks have a bug, it's tripping on https://github.com/conan-io/conan-center-index/blob/a859c2bdd26f68494cfde69bac1061b979bfc368/recipes/armadillo/all/conanfile.py#L182 which matches the regex from what I can figure out

```diff
- # self.requires("intel-mkl/version@user/channel, override=True) in their consumer 
+ # set `override=True` when calling `self.requires` which specifies `intel-mkl/version@user/channel` in their consumer
```

should be enough to work around it

_Originally posted by @prince-chrismc in https://github.com/conan-io/conan-center-index/issues/15109#issuecomment-1372841368_

**Comment by samuel-emrys** [comment]
For tracking, the offending code is:
https://github.com/conan-io/hooks/blob/445fac5d906e0dab4de660bcd540d65406130f2f/hooks/conan-center.py#L914-L916

I think the resolution would be something akin to:
```diff
- match = re.search(r'self.requires\(.*override=True.*\)', conanfile_content)
+ match = re.search(r'^\s*self.requires\(.*override=True.*\)', conanfile_content)
```
which makes sure that there's only whitespace preceeding the `self.requires(...)` statement

**Comment by prince-chrismc** [comment]
❤️

**Comment by uilianries** [comment]
@prince-chrismc This issue has been fix. Thanks to @samuel-emrys ! 👏
