### ISSUE TITLE
hook activation in Conan 2.X

### ISSUE THREAD

**Issue by Tobulus** [conan-io/hooks#490]
Hi,

the readme mentions this command to activate the hooks:
`$ conan config set hooks.conan-center`

How is that done in Conan 2.x?

**Comment by memsharded** [comment]
Hooks in 2.0 are activated by just placing them in the cache, there is no another activation step necessary in the config.

**Comment by uilianries** [comment]
@Tobulus please, read https://docs.conan.io/2/reference/extensions/hooks.html#storage-activation-and-sharing for more information.
