### ISSUE TITLE
skip compile test_package

### ISSUE THREAD

**Issue by lazyze** [conan-io/hooks#499]
how to skip compile test_package and test_v1_package

**Comment by memsharded** [comment]
Hi @lazyze 

It is not clear what you mean and in what context.
If using conan tool, define ``conan create ... -tf=""`` (in Conan 2.0) or ``-tf=None`` (Conan 1.X)

In ConanCenter, test_v1_package can be removed, but ``test_package`` is mandatory and must run and work

**Comment by memsharded** [comment]
Good, then I think we can close this ticket as responded if that is what you needed. Thanks!
