### ISSUE TITLE
[conan-center_reviewer] Should we consider fPIC for installer and header-only?

### ISSUE THREAD

**Issue by uilianries** [conan-io/hooks#50]
Hi!

Question about the hook `conan-center_reviewer`. It checks the `fPIC`, but some recipes does not have `options`, like installers and header-only. Maybe we could skip `fPIC` check (including log) if there is no `option` attribute computed.

Regards!

**Comment by danimtb** [comment]
Yeah, it is an optimization. Could be done for next iteration
