### ISSUE TITLE
Wrong documentation on how to activate the hooks

### ISSUE THREAD

**Issue by elvisdukaj** [conan-io/hooks#531]
To activate the hook the documentation says:

```
$ conan config set hooks.conan-center
```

But with conan 2+ I have an error:

```
$ conan config set hooks.conan-center                                            
usage: conan config [-h] [-v [V]] [-cc CORE_CONF] {home,install,install-pkg,list,show} ...
conan config: error: argument subcommand: invalid choice: 'set' (choose from 'home', 'install', 'install-pkg', 'list', 'show')
```

What is the right way to activate hooks?

**Comment by uilianries** [comment]
Hello @elvisdukaj! Your question looks duplicated to https://github.com/conan-io/hooks/issues/506

Please, take a look there first. Regards!

**Comment by elvisdukaj** [comment]
Thank you for the feedback! This issue can be closed than 😀
