### ISSUE TITLE
[conan center] check there is no author attribute

### ISSUE THREAD

**Issue by SSE4** [conan-io/hooks#97]

**Comment by danimtb** [comment]
Please read more about this in this comment https://github.com/conan-io/hooks/pull/92#issuecomment-536943053

**Comment by Croydon** [comment]
I agree with the argument that the author attribute shouldn't be added to CCI recipes (and therefore in Bincafters) since the entire community is maintaining them, putting there just one name is unfair, putting there all is unmanageable
